runtime: python312
entrypoint: gunicorn -b :$PORT app:app
service: default
instance_class: F1

env_variables:
  GAE_ENV: "standard"

handlers:
  # Handle static files
  - url: /static
    static_dir: catcare/static
    secure: always
  
  # All other URLs are handled by the app
  - url: /.*
    script: auto
    secure: always

beta_settings:
  cloud_sql_instances: "${CLOUD_SQL_INSTANCE}"

includes:
  - env_variables.yaml