"""Add videos and multiple photos support

Revision ID: d13b26374e5a
Revises: 
Create Date: 2024-12-16 18:54:17.185111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd13b26374e5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('videos', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('needs', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('photo')
        batch_op.drop_column('need')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'case', ['case_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('need', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('needs')
        batch_op.drop_column('videos')
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
