"""Add arrays and keep old columns

Revision ID: eb55919c8090
Revises: d13b26374e5a
Create Date: 2024-12-17 11:07:57.526233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb55919c8090'
down_revision = 'd13b26374e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('need', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('need')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
